### ISSUE TITLE
Safari-specific filter issues: Please report troubleshooting information

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uBOL-home#358]
This is a new thread to report troubleshooting information for those facing filtering issues.

**DO NOT** post screenshots **UNLESS** requested by volunteers here. However **troubleshooting information is required**.

When facing filtering issues such as lack of expected filtering, please do the following:
- Visit a webpage where you suffer filtering issues
- Share the URL of that webpage here, wrap URL in backticks `` ` `` to prevent live links
- Click the _chat_ icon in the popup panel
- Expand "Troubleshooting information" at the bottom
- Copy/paste content here, wrapped around three backticks `` ``` `` lines (for proper code block rendering)

Thank you.

**Comment by gorhill** [comment]
> registerContentScripts:

Unfortunately, it seems to be a `registerContentScripts` malfunction, and removing/reinstalling the extension is only what might work.

**Comment by sol1tary** [comment]
> > registerContentScripts:
> 
> Unfortunately, it seems to be a `registerContentScripts` malfunction, and removing/reinstalling the extension is only what might work.

Unfortunately, reinstalling didn't help, it's not a big issue though. Thanks!

**Comment by stephenhawk8054** [comment]
> The worry is about DNR rule counts, since each entry in requestDomains will have to be spin off as a single DNR rule

Is this from Safari's official fix or from the workaround?

**Comment by gorhill** [comment]
Looks like in Safari there is a [150K "content blocking" rules limit](https://developer.apple.com/forums/thread/756931). Their declarativeNetRequest implementation translates DNR rules into internal "content blocking" rules, so it looks this might be an issue whether the fix is on my side or their side. Ideally, in the future they would extend their ["content blocking" rule syntax](https://developer.apple.com/documentation/safariservices/creating-a-content-blocker) to support the equivalent of DNR's `requestDomains`. They already have code for `if-domain` to match against an array of domains, which is essentially what `requestDOmains` does.

**Comment by sol1tary** [comment]
> > Unfortunately, reinstalling didn't help, it's not a big issue though. Thanks!
> 
> Did you quit Safari after removing the extension? I suffered the malfunction in the past on an iPad, at which time I removed the extension. Eventually I re-installed it after a while and `registerContentScripts` worked as expected.

Yeah, it's still the same. Do I need to do a "full" reinstall? Because after reinstalling, all my filters and settings just come back automatically

**Comment by gorhill** [comment]
> Do I need to do a "full" reinstall?

I would say yes because I suspect there is storage corruption related to `registerContentScripts`, but I wouldn't know how to force all the extension data to be completely removed.

**Comment by MineGene** [comment]
@sol1tary @gorhill 

Have either of you found a way to fully reset the app back to defaults, clearing all extension data successfully?

I've tried various times to do this, but it hasn't worked, including:
- uninstalling app
- turning off iCloud Safari sync
- clearing Safari data
- clearing iCloud Safari data
- rebooting

I can't think of any additional places the extension data would be kept to be able to reset the app.

**Comment by vitorgalvao** [comment]
> I can't think of any additional places the extension data would be kept

All the steps you described were about *Safari* data, not the extension’s. There’s `~/Library/Containers/net.raymondhill.uBlock-Origin-Lite` and `~/Library/Containers/net.raymondhill.uBlock-Origin-Lite.Extension`.

**Comment by MrAlex94** [comment]
`https://www.ispreview.co.uk/`

```

name: uBlock Origin Lite
version: 2025.529.1838
browser: Safari Mobile 604 (ios)
filtering:
 site: complete
 default: complete
rulesets:
 annoyances-others
 adguard-spyware-url
 ublock-badware
 adguard-mobile
 annoyances-overlays
 ublock-filters
 block-lan
 annoyances-cookies
 easylist
 pgl
 urlhaus-full
 easyprivacy
registerContentScripts:
```

**Comment by gorhill** [comment]
Don't quote other people's troubleshooting information please, post your own troubleshooting information, we do not want this thread to end up being a long list of duplicated information.

**Comment by sol1tary** [comment]
> > settings seem to have remained the same, strangely
> 
> That is not strange, all the settings are stored using `storage.local`, and I haven't seen issues with this API.
> 
> The API failing is `scripting.registerContentScripts`, and there is something for Safari to fix there, but I guess they would need to reproduce the issue to figure out why it keeps failing despite being called with proper arguments. When this happened on my side, even the [most simplest case of script registration](https://gist.github.com/gorhill/8dadb741bdb4cf4c7a793f453278b6a0) failed.
> 
> When searching for the error message ("Failed to add content script") in WebKit code base, there was only one place found matching the error message, and this was <https://github.com/WebKit/WebKit/blob/2246a2aa28d527e129ebec66183569db035fdc8a/Source/WebKit/Shared/Extensions/_WKWebExtensionRegisteredScriptsSQLiteStore.mm#L234> -- so it looks like all calls to `SQLiteDatabaseExecute` starts to fail, which I guess is something that would happen with SQLite storage corruption.
> 
> When that happened to me I uninstalled uBOLite from the iPad and re-enabled Ghostery. Time passed and eventually when I came back to work more on the Safari version, I gave a try to re-install a locally build version of uBOL, and it started to work normally. So far it's still working.
> 
> The latest version, [uBOLite_2025.604.1144](https://github.com/uBlockOrigin/uBOL-home/releases/tag/uBOLite_2025.604.1144-beta),  should properly report the full error message in troubleshooting information, and I am guessing it will be the same as the one at the gist link above.


Hey, is it normal that the last version on Testflight is still 529.1839?

**Comment by gorhill** [comment]
Just spotted a fix in WebKit related to scripting.registerContentScripts API: <https://github.com/WebKit/WebKit/pull/46581>

Hopefully this is related to the issue experienced in uBOL.

**Comment by meshuggah44** [comment]
> > Is there any info I can provide to try to figure out why it just doesn't work on my work mac?
> 
> What is the Safari version on that mac?

Same as the one in my personal one, where everything is working: Version 18.5 (20621.2.5.11.8)

**Comment by gorhill** [comment]
Maybe your work mac has policies to prevent installation of non-vetted Safari extensions.

**Comment by ftgjhf** [comment]
So after the update today, everything worked perfectly for a few hours. I also confirmed there were no errors in the troubleshooting information.
```
name: uBlock Origin Lite
version: 2025.604.1144
browser: Safari Mobile 604 (ios)
filtering:
 site: complete
 default: complete
rulesets:
 ubol-tests
 ublock-filters
 adguard-spyware-url
 easylist
 pgl
 ublock-badware
 urlhaus-full
 easyprivacy
 adguard-mobile
```

Now, the old issue is back, and I can see some ads and ad remnants. Here’s the troubleshooting information.
```
name: uBlock Origin Lite
version: 2025.604.1144
browser: Safari Mobile 604 (ios)
filtering:
 site: complete
 default: complete
rulesets:
 ubol-tests
 ublock-filters
 adguard-spyware-url
 easylist
 pgl
 ublock-badware
 urlhaus-full
 easyprivacy
 adguard-mobile
registerContentScripts: Error: Invalid call to scripting.registerContentScripts(). Failed to add content script
```

**Comment by dwight1989-coder** [comment]
Yes this makes sense,stupidly I was under the   impression that once it was posted to Github it was available for testflight testing! Thank you for the help!

> I don't understand you mean. If you mean the newer version `2025.612.1348`, it has been submitted to Testflight and is waiting for approval from Apple.

**Comment by dwight1989-coder** [comment]
Is it a known issue Reddit ads and X-Twitter ads are still not being blocked? 

![Image](https://github.com/user-attachments/assets/e0b90c35-1159-45fd-bca3-2283bc9232af)
![Image](https://github.com/user-attachments/assets/eac884db-b31f-4bef-a058-4a714b7b4c39)

**Comment by stephenhawk8054** [comment]
> **troubleshooting information is required.******

**Comment by dwight1989-coder** [comment]
> troubleshooting information is required.

Troubleshooting information
name: uBlock Origin Lite
version: 2025.604.1144
browser: Safari Mobile 604 (ios)
filtering:
 site: optimal
 default: optimal
user rules: 1
rulesets:
 ubol-tests
 adguard-spyware-url
 annoyances-others
 annoyances-social
 ublock-badware
 adguard-mobile
 annoyances-overlays
 ublock-filters
 annoyances-cookies
 annoyances-widgets
 easylist
 pgl
 easyprivacy
registerContentScripts: Error: Invalid call to scripting.registerContentScripts(). Failed to add content

**Comment by stephenhawk8054** [comment]
Again, it's ` registerContentScripts: Error: Invalid call to scripting.registerContentScripts(). Failed to add content` issue that makes scriptlets and cosmetic filtering fails, which are needed for twitter and reddit ads. You'll need to wait until Apple lands the fixes to stable Safari.

**Comment by stephenhawk8054** [comment]
> If my memory serves me right it is FIXED* in Safari preview correct?

No, that was another issue.

This issue is different, and what we _**suspect**_ is this issue is related to https://github.com/uBlockOrigin/uBOL-home/issues/358#issuecomment-2962846398 , but we don't know when the fix will land on Technology Preview or Stable and we are not sure whether that fix in WebKit is actually the same as this one.

**Comment by dwight1989-coder** [comment]
Ahhhh I see,Again it is greatly appreciated you pointing that out to me! I guess heres to hoping right? As a side question do you know anyone who have tested it on the latest safari preview?

**Comment by dwight1989-coder** [comment]
> > If my memory serves me right it is FIXED* in Safari preview correct?
> 
> No, that was another issue.
> 
> This issue is different, and what we _**suspect**_ is this issue is related to [#358 (comment)](https://github.com/uBlockOrigin/uBOL-home/issues/358#issuecomment-2962846398) , but we don't know when the fix will land on Technology Preview or Stable and we are not sure whether that fix in WebKit is actually the same as this one.

Interesting to note I used the the safari profile workaround and magically its working correctly,I know it will malfunction again regardless very interesting!

**Comment by krystian3w** [comment]
They certainly didn't fix it in the first Safari 26 beta, so we may have to wait up to 2 years until they fix it in Safari 27.

Worst case like when we have to delete all iOS memory to have a fresh default Safari profile in iOS (no way to fix with a normal upgrade from 18.6 to 26 or 27).

**Comment by gorhill** [comment]
See [Safari Release Notes](https://developer.apple.com/documentation/safari-release-notes/) to find out which fixes landed, search for "Web Extensions".

**Comment by dwight1989-coder** [comment]
> They certainly didn't fix it in the first Safari 26 beta, so we may have to wait up to 2 years until they fix it in Safari 27.
> 
> Worst case like when we have to delete all iOS memory to have a fresh default Safari profile in iOS (no way to fix with a normal upgrade from 18.6 to 26 or 27). Bush League Garbage isnt it now? just inexcusable.Thanks for clearing this up!

**Comment by gorhill** [comment]
I would like to keep the thread here mostly for troubleshooting info and specific issue with technical information. Currently too many notifications for what is mostly chatter.

**Comment by gorhill** [comment]
> My phone overheats

> `stevenblack-hosts`
> `dpollock-0`

I am going to have to prevent many of these large lists from being available for Safari. The way Safari's DNR implementation works is to convert DNR rules into Safari content blocking rules, and DNR rules with large number of `requestDomains` entries is quite possibly causing performance issues when converted to Safari content blocking rules.

Last time I looked there was over 92K `requestDomains` entries in just `stevenblack-hosts`, which would translate into over 92K distinct Safari content blocking rules, just for that one list. And that gets worse when taking into account that all these entries are also mirrored into strict-block rules.

I will have to add a warning in TestFlight to avoid enabling too many lists in Safari, and prevent these large lists from ending in Safari uBOL.

> I cannot revert any changes from the filtering list.

Are you waiting long enough after disabling one of these large lists before quitting Safari? Even on a M4, it takes long seconds for Safari to convert DNR rules to Safari content blocking rules with just default lists, so with optional large lists such as `stevenblack-hosts` or `dpollock-0`, I gather it must takes even longer.

> `registerContentScripts`

Your installation is essentially broken, see <https://bugs.webkit.org/show_bug.cgi?id=294298>.

**Comment by stephenhawk8054** [comment]
> Thanks for clarifying it, I'm disabling them. The overheating problems seems to not have been fully solved even after disabling those large lists. Maybe because of the registerContentScripts problem?

Try reinstall uBOL and keep default settings and test again.

> So, do we have to wait for Apple to fix that WebKit bug?

Yes, there's nothing else we can do except waiting for Apple's fix to land on the releases.

**Comment by gorhill** [comment]
> Maybe because of the registerContentScripts problem?

No. If you suffer a overheating problem, you need to investigate more to confirm this is really linked to uBOL. The whole DNR engine is Safari code, there is no uBO code executing for filtering network requests, and as for registered content scripts, I have not noticed any performance issues, and when I profiled other platforms there was no issue.

**Comment by dwight1989-coder** [comment]
Is it normal behavior for Safari to stop adblocking capabilities after a period of hours (Without restarting Safari) through the app switcher? Thus having to start over creating new profile and reloading UBL extension?

**Comment by gorhill** [comment]
No it's not. Need troubleshooting information as asking in thread title.

**Comment by gorhill** [comment]
- Navigate to a webpage with ads which you expect uBOL should block
- Bring up uBOL's popup panel
- Click _chat_ icon
- Click "Troubleshooting information" at the bottom of newly opened page
- Copy/paste content of "Troubleshooting information" here

**Comment by MineGene** [comment]
Just updated to the latest beta, getting the below after a while of running it:

```

name: uBlock Origin Lite
version: 2025.624.1458
browser: Safari Mobile 604 (ios)
filtering:
 site: complete
 default: complete
rulesets:
 ubol-tests
 adguard-spyware-url
 annoyances-others
 annoyances-social
 ublock-badware
 adguard-mobile
 annoyances-overlays
 ublock-filters
 annoyances-cookies
 annoyances-widgets
 easylist
 pgl
 easyprivacy
registerContentScripts: Error: Invalid call to scripting.registerContentScripts(). Failed to add content script

```

(Already discussed previously in issue)

**Comment by Ickis** [comment]
I am now using the latest beta of uBOL on my iPad, formerly I used Firefox Focus in Safari for ad blocking. 

I recognized a difference in the behaviour of uBOL and Firefox Focus: Firefox Focus also blocks ads in Webviews used by apps like BlueSky or Reeder (Atom feed reader), uBOL does not block anything in those webviews. 

I‘d like to request the feature that uBOL also works in Webviews and not only in the Safari browser if possible (maybe Firefox Focus does stuff uBOL cannot do?).

**Comment by hotsno** [comment]
Seeing ads on `https://anilist.co/manga/171729/Love-Bullet/`

```

name: uBlock Origin Lite
version: 2025.624.1458
browser: Safari Mobile 604 (ios)
filtering:
 site: complete
 default: complete
rulesets:
 ublock-filters
 easylist
 pgl
 ublock-badware
 easyprivacy
 adguard-mobile
registerContentScripts: Error: Invalid call to scripting.registerContentScripts(). Failed to add content script.
```

**Comment by nomesc** [comment]
> Are you waiting long enough after disabling one of these large lists before quitting Safari? Even on a M4, it takes long seconds for Safari to convert DNR rules to Safari content blocking rules with just default lists

Is there a way to implement a status bar to know when the process finished or if it previously failed?

**Comment by gorhill** [comment]
Yes, I was informed that both requestDomains and registerContentScripts issues are fixed in 18.6 beta 2. Once these fixes reach stable version of Safari, I will publish an official stable release of uBOL.

**Comment by MineGene** [comment]
> uBOL 2025.624.1458(1022.1458) has now stopped showing in the iOS Safari (18.5) extensions list, which means I am unable to use uBOL at all in Safari.
> Due to this I am unable to get any in-app logs from uBOL.
> 
> I have tried:
>  - Reinstalling
>  - Rebooting
>  - Trying to enable the extension under both Safari > Extensions, and Settings > Apps > Safari > Extensions. It's not visible in either location.
>  - Force closing Safari and reopening 
> 
> I am not seeing this issue on macOS Safari.

@gorhill is there something I can do to debug this that might be useful for future versions?

I cannot get this uBOL update to show in Safari extensions no matter what I try.

**Comment by ftgjhf** [comment]
Today’s Safari Technology Preview has this
>Fixed calling scripting.registerContentScripts() sometimes returning the error: “Error: Invalid call to scripting.registerContentScripts(). Failed to add content script.” ([296093@main](https://commits.webkit.org/296093@main)) (153001967)
https://webkit.org/blog/17201/release-notes-for-safari-technology-preview-223/

**Comment by stephenhawk8054** [comment]
Yes, that's element zapper: https://github.com/gorhill/uBlock/wiki/Element-zapper . It's meant to be temporary.

Element picker is not implemented yet: https://github.com/uBlockOrigin/uBOL-home/issues/325

**Comment by dwight1989-coder** [comment]
With Latest Testflight that was pushed today (7-17),Creating a custom Filter and saving changes it doesn't save the changes on 1st attempt,however on second attempt it does complete 

<img width="1290" height="2796" alt="Image" src="https://github.com/user-attachments/assets/1a906be0-0ed3-4a50-976a-d19bb2c2cc66" />

blocking the element picked.

**Comment by dwight1989-coder** [comment]
Okay I do apologize,can you provide steps to send information? Also when pressing Preview>Create it does seem to save changes and block the element for the record! 👍 Thank you for all of you're hard work on this project!

**Comment by gorhill** [comment]
@dwight1989-coder 

[Dashboard: Develop](https://github.com/uBlockOrigin/uBOL-home/wiki/Dashboard:-Develop):

> Non-technical users should avoid tampering with features requiring advanced knowledge about the inner workings of a browser, and more specifically about the [DNR API](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest). Misusing the tools available in the Develop pane could cause harm to your privacy and security.

You keep ignoring what is asked in top comment. I am going to ask you to stop posting comments here, and use [Discussions](https://github.com/uBlockOrigin/uBOL-home/discussions) instead.

**Comment by muli** [comment]
Hi,

I stupidly unregistered myself from testing the app on TestFlight, and now the beta is full.
Is there a plan to open the beta to more people (assuming you didn't exceed Apple's 10k (?) limit)?

Thanks for your amazing work regardless.

**Comment by unebomberq** [comment]
> Hi,
> 
> In an attempt to do a "full" removal of the beta and re-install it again, I stupidly unregistered myself from testing the app on TestFlight, and now the beta is full. Is there a plan to open the beta to more people (assuming you didn't exceed Apple's 10k (?) limit)?
> 
> Thanks for your amazing work regardless.



X2 Now I can't have access to it

**Comment by ftgjhf** [comment]
uBOL mostly works for me now, but I did find two edge cases where it doesn’t.
The first is the same as what’s reported above. When you close Safari and open it, the first website is not completely filtered. Here’s an example: On https://www.forbes.com/sites/jabariyoung/2025/07/17/meet-the-investor-who-sold-his-coffee-shop-to-disrupt-venture-capital/, I see a white banner at the bottom of the screen. 
![Image](https://github.com/user-attachments/assets/d2e46f77-aed8-4241-a67f-11ffb7d8c983)

https://ublockorigin.github.io/uBOL-home/tests/test-filters.html looks like this
![Image](https://github.com/user-attachments/assets/d414d837-582a-44a4-95e5-cdb8ff11647d)

Reloading the website sometimes once and sometimes twice changes this. On the Forbes website, there’s no more white banner. The test website looks like this 
![Image](https://github.com/user-attachments/assets/4d1bb6f3-5e00-49ff-9d83-ec418e22f562). This is also the case when you navigate to these websites from one. 

This is doesn’t happen 100% of the time, but it’s pretty frequent. You might need a few tries before you get this result.

The other case is switching between Private (incognito) tabs and normal tabs. The websites break as above, but refreshing doesn’t seem to fix them. Any website you navigate too also has this problem. You have to exit Safari and open it again.

name: uBlock Origin Lite
version: 2025.723.1810
browser: Safari Mobile 604 (ios)
filtering:
 site: complete
 default: complete
rulesets:
 ublock-filters
 ubol-tests
 adguard-spyware-url
 easylist
 ublock-badware
 pgl
 easyprivacy
 adguard-mobile
registerContentScripts: Error: Invalid call to scripting.registerContentScripts(). Failed to add content script.

**Comment by stephenhawk8054** [comment]
> registerContentScripts: Error: Invalid call to scripting.registerContentScripts(). 

It's Safari's bug. You need to wait until its fixes land.

**Comment by gorhill** [comment]
**PLEASE**, read carefully:

> No need to post screenshots until requested by volunteers here

Posting screenshots make the threads very difficult to handle. If the instructions keep getting ignored, I will have to do something to keep this project maintainable.

**Comment by meshuggah44** [comment]
macOS 15.6 and iOS 18.6 came out yesterday, and I believe the fixes to `registerContentScripts` were included in them. It's working much better for me at least.

> Hello, uBOL doesn't work correctly when Safari is freshly launched (it seems on iOS only). Here's a GIF showing a website displaying an ad right after opening Safari, and then - after a few seconds - reloading the same site results in the ad being blocked. I'm using the latest iOS version (18.6) and the latest uBOL TestFlight build (2025.723.1810).

This is something I also noticed. Whenever Safari is freshly launched (to me it happens mostly on macOS), uBOL takes a while to properly load. During that time, it doesn't block ads, and when clicking on the toolbar icon it'll show an empty window. After 10 seconds or so it'll show the usual options - blocking level slider, create custom filter, open dashboard, etc).

**Comment by volcbs** [comment]
>Can you try unchecking the setting "Enable strict blocking" in Settings pane in the dashboard and see if this has an effect on the launch behavior?

There doesn't seem to be any difference to me. I do notice that when you enable `adguard-mobile`, the loading time gets longer. At first I thought it was related to the filter number (mine is 131k when `adguard-mobile` is activated), but it seemed the problem is on `adguard-mobile` since I haven't had any problems as I don't enable that filter.
<details> 
  <summary>Troubleshooting information </summary>
 name: uBlock Origin Lite
version: 2025.723.1810
browser: Safari 605 (mac)
filtering:
 site: complete
 default: complete
rulesets:
 ubol-tests
 annoyances-others
 annoyances-social
 ublock-badware
 jpn-1
 annoyances-overlays
 ublock-filters
 ublock-experimental
 annoyances-cookies
 annoyances-widgets
 easylist
 pgl
 idn-0
 easyprivacy
</details>

**Comment by stephenhawk8054** [comment]
Can you test with uBOL default settings? (Don't enable any annoyances lists)

**Comment by meshuggah44** [comment]
> Can you try unchecking the setting "Enable strict blocking" in _Settings_ pane in the dashboard and see if this has an effect on the launch behavior?

I tried, but it didn't have any effect.

What I reckon is causing this is the amount of lists enabled. These are the ones I'm using for instance:

```
name: uBlock Origin Lite
version: 2025.723.1810
browser: Safari 605 (mac)
filtering:
 default: complete
rulesets:
 adguard-spyware-url
 annoyances-others
 annoyances-social
 ublock-badware
 annoyances-overlays
 ublock-filters
 ublock-experimental
 annoyances-cookies
 ita-0
 easylist
 pgl
 annoyances-widgets
 spa-1
 easyprivacy
```

I tried disabling all lists under the `annoyances` section, and uBOL loaded instantly after launching Safari, so it might be related to hitting the macOS/iOS rules limit.
Other Safari content blockers such as wBlock, Adguard, Wipr, circumvent this by separating the rules into different extensions (as in, it's still a single app, but within Safari it shows as separate extensions). Maybe the same could be done for uBOL?

For example, when installing wBlock the following extensions show up in Safari's settings:
- wBlock Ads & Privacy
- wBlock Advanced
- wBlock Annoyances
- wBlock Custom
- wBlock Foreign & Experimental
- wBlock Security & Multipurpose

**Comment by gorhill** [comment]
The official first official release version for Safari is now available: <https://apps.apple.com/us/app/ublock-origin-lite/id6745342698>

Requirement is Safari 18.6.

I will close this thread now that the official release version is available. Filter issues should be filed through the "Report an issue" item in the popup panel.

That for all who contributed with feedback.

I wasn't able to post screenshots for iPhone in the Safari App Store because I do not have access to an iPhone (I used screenshots from Firefox's device emulator in its dev tools for the time being). If a volunteer can contribute screenshots for iPhone, that would be great. I need three screenshots:

- one for the popup panel (brought up while browsing `https://arstechnica.com/health/2025/08/radioactive-wasp-nests-spring-up-in-decadesold-nuclear-site-in-south-carolina/`)
- one for the _Settings_ pane in the dashboard
- one for the _Filter lists_ pane in the dashboard

Be sure the screenshots do not contain personal information, and that uBO Lite is set to default configuration.

**Comment by meshuggah44** [comment]
> The official first official release version for Safari is now available

Is it geo-restricted? It says it's not available in my region (I'm in the EU)

**Comment by CirnoT** [comment]
> It's not geo restricted (to my knowledge), but I think it might take 24h to propagate everywhere:
> 
> > Please note that it can take up to 24 hours for apps to become available on the App Store after release

It seems to be propagated everywhere now except for UK and EU countries, so there is definitely something going on. Perhaps Apple requires you select under which EU terms you want to distribute.

**Comment by u-RraaLL** [comment]
Some people are reporting needing to force close safari for the settings page to start working: https://www.reddit.com/r/uBlockOrigin/comments/1mi8fd6/comment/n71r13n/

**Comment by gorhill** [comment]
> I will have to check again.

Ok, there was something to set-up re. "Digital Services Act", which I have now filled. Hopefully this will make the extension available in the E.U.

**Comment by gorhill** [comment]
> If I'm not wrong, due to the slow conversion to DNR of Safari, users will need to wait a bit before the conversion is finished.

Yeah, most likely related to this.

**Comment by gorhill** [comment]
> when users opening settings page the first time

The thing is that the conversion to dNR occurs at installation or update time, without necessarily the dashboard being opened -- unlike most other content blockers, uBOL's dashboard doesn't automatically open at install time, I really want it to be install-and-forget.

Also, since the conversion is done internally by Safari's framework, I am not sure there is a way for uBOL to know when it occurs or when it's complete. I will have to test some API call to find out if there is a way to know, and if so then maybe reflect this on the toolbar icon (as is done with uBO at launch).

**Comment by gorhill** [comment]
Important issues were fixed in Safari 18.6, the extension was not functioning as intended in pre 18.6 even if at first glance it seemed to work, behind the scene it was not filtering reliably as it should, and there was also a potential issue breaking all content scripts.

For lower version, best to use another content blocker.

**Comment by infinitepower18** [comment]
Actually Safari 18.6 can run on macOS versions all the way back to Ventura, so it may be good to reduce the min requirement for the macOS app to 13.0 (or 13.7) for those old Macs that can't get the latest OS.

For iOS, Safari updates are tied with the OS so Safari 18.6 is only available on iOS 18.6. You should be able to bump the requirement in the Xcode project settings of the container app.

<img width="717" height="92" alt="Image" src="https://github.com/user-attachments/assets/c3ae3f1f-5b7f-4d37-a26b-a6fe8edc9b2a" />

**Comment by gorhill** [comment]
> when users opening settings page the first time

Thanks for the information, I will lower the macOS version to 13.7.

As for iOS, if I set the minimum version for the wrapper app to "18.6", I can no longer build for my iPad device. Restoring to "18.0" I can again see the iPad device as valid run destination.

**Comment by infinitepower18** [comment]
That's strange, my devices still show up as valid run destinations if I try to set my app to 18.6. Are you using Xcode 16.4?

<img width="633" height="425" alt="Image" src="https://github.com/user-attachments/assets/990902fa-3927-464e-a69c-c90c9e1638e6" />

**Comment by stephenhawk8054** [comment]
> Around 24k rules (converted), I have enabled filters a bit slower between each like proposed by @stephenhawk8054 above and it fixed the issue, thanks to both of you for pointing me to the solution.

@gorhill Hmm... How about uBOL will make other lists disabled to be selected for about 5s each time user enable/disable a list?

At least it would prevent users enabling other lists too fast and causing unexpected issues.

**Comment by gorhill** [comment]
Since there is now an official stable release for Safari, this thread is no longer needed, therefore I will close it.

Thanks for all the feedback which led to the release of uBOL on Safari, and thanks to David and Michael from Apple who assisted me through email in helping make uBOL happen in Safari.

Filter issues should be reported using the "Report an issue" entry in the popup panel, and issues with the extension itself can be reported here as is done for any other platform.
