### ISSUE TITLE
Can't visit device specification pages from Apple (with redirects) [macOS 26]

### ISSUE THREAD

**Issue by Tekl** [uBlockOrigin/uBOL-home#409]
### Prerequisites

- [x] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality by using the _chat_ icon in the popup panel.
- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367) or [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [x] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBOL-home/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [x] The issue is not present after disabling uBO Lite in the browser.

### I tried to reproduce the issue when...

- [x] uBO Lite is the only extension.
- [x] using a new, unmodified browser profile.

### Description

In the system settings of macOS there's a link to the specifications of the device in the help menu. Even when no filter list is enabled, Safari in macOS 26 Dev Beta 5 refuses to open that link, which is a redirect link.

On macOS 15.6 with Safari 18.6 everything seems to be fine.

### A specific URL where the issue occurs.

```text
https://support-sp.apple.com/sp/index?page=cpuspec&cc=000996&lang=de-DE_DE
```

### Steps to Reproduce

1. Open System Settings in macOS
2. Open Help menu
3. Click on "<Device> specification"

or just visit the provided link

### Expected behavior

The URL should redirect to:
https://support.apple.com/de-de/111901

### Actual behavior

Safari shows this message:

A problem has repeatedly occurred with "https://support-sp.apple.com/sp/index?page=cpuspec&cc=000996&lang=de-DE_DE"

Reload Website

### uBO Lite version

2025.804.1931 (1063.1931)

### Browser name and version

Safari 26.0 (21622.1.21.11.3)

### Operating system and version

macOS 26 Dev Beta 5 (25A5327h)

**Comment by gorhill** [comment]
You disabled all other default filter lists?

I could not reproduce using Chromium, I can't investigate for macOS at the moment.

**Comment by Tekl** [comment]
It only happens in macOS with Safari on macOS 26, macOS 15.6 seems to be fine.

**Comment by gorhill** [comment]
From now on, any issue which is reproducible in beta version of a browser but not the stable version will be declined. We welcome people investigating those issues specific to beta versions and sharing their findings if ever it is determined that the issue is _really_ with uBOL (along with the specific code in uBOL), otherwise the issues will have to be assumed to be with the beta versions of browser or OS.

**Comment by Tekl** [comment]
Okay, sorry. I thought it would be helpful to get uBOL adopted to the coming systems as soon as possible.

**Comment by nuthub-io** [comment]
It looks like I can’t install the stable version of uBlock Origin lite on MacOS Tahoe beta 5. It also didn’t work for the public beta. 

The installation works great on IOS 26 public beta and beta 5. But I can’t download the official app though the app store. Is there a compatibility problem there?

**Comment by James76931** [comment]
Safari/macOS/iOS/iPadOS 26 should be out around mid-September @gorhill :)
Worth keeping an eye out for the release candidate a week prior as that's the stable build given to developers early. There could be a release candidate 2 but this is not common.

**Comment by nuthub-io** [comment]
I would love an early build! uBlock Origin Lite is by far the best ad blocker on an Apple device.

**Comment by Tekl** [comment]
@nuthub-io I had no problems installing uBOL in macOS 26 Beta 5. What's the error message?

**Comment by Tekl** [comment]
That must be a beta issue. The App Store had some problems in the betas (my update page was empty for months). Do you have restarted your Mac and tried again?

**Comment by nuthub-io** [comment]
@Tekl I did! I restarted my Mac, signed out and logged in again within the app store, removed the cache of the app store, upgraded from the public beta to beta 5, ... If it was possible for you to install it then it will be a beta problem for sure. Installing it on IOS 26 beta 5 isn't a problem. I just wanted to be sure it wasn't a compatibility problem

**Comment by Tekl** [comment]
It also does not work here with beta 6. I disabled everything possible in uBOL. Other Blockers like Adguard for Safari or Wipr 2 don't have this issue.

**Comment by lucasyvas** [comment]
It's a webkit issue that has been resolved and not shipped. It's a page crash.

**Comment by stephenhawk8054** [comment]
> When is stable 26 set to be released?

@gorhill I think iOS 26 is available for stable now.

**Comment by stephenhawk8054** [comment]
Please record video of what are the steps to reproduce `install doesn't work` or whatever doesn't work. We can't investigate if the description is too vague.

Usually right after you install, you need to wait some time Safari to convert the DNR rules. Safari's conversion is very slow.

**Comment by nuthub-io** [comment]
This is the problem I have when trying to install uBlock Origin Lite. 

As you can see the wheel keeps spinning and nothing else happens. I removed the cache of Safari and the App store. Logged out and in again. Still the same issue. 

https://github.com/user-attachments/assets/c25eaa2a-d780-450a-a077-ce8a7137cea2

**Comment by stephenhawk8054** [comment]
> As you can see the wheel keeps spinning and nothing else happens

I can't reproduce. I just uninstalled uBOL and went to app store to install it.

**Comment by nuthub-io** [comment]
Any idea how I can fix it?
